@startuml

title __MEDIA's Class Diagram__\n

  package com.m2i.poe {
    package com.m2i.poe.media {
      class Author {
          - id : int
          - firstName : String
          - lastName : String
          + Author()
          + Author()
          + getId()
          + setId()
          + getFirstName()
          + setFirstName()
          + getLastName()
          + setLastName()
      }
    }
  }
  

  package com.m2i.poe {
    package com.m2i.poe.media {
      class Book {
          - nbPage : int
          + getNbPage()
          + setNbPage()
          + Book()
          + Book()
          + getNetPrice()
      }
    }
  }
  

  package com.m2i.poe {
    package com.m2i.poe.media {
      class Cart {
          - cartRowList : List<CartRow>
          + Cart()
          + getMediaList()
          + getTotalNetPrice()
          - isMediaInCart()
          + addItem()
          + removeItem()
          + affichePanier()
      }
    }
  }
  

  package com.m2i.poe {
    package com.m2i.poe.media {
      class CartRow {
          - quantity : int
          + CartRow()
          + CartRow()
          + getNetPrice()
          + increment()
          + decrement()
          + getQuantity()
          + getTitle()
          + getMedia()
      }
    }
  }
  

  package com.m2i.poe {
    package com.m2i.poe.media {
      class Cd {
          - nbPage : int
          + getNbPage()
          + setNbPage()
          + Cd()
          + Cd()
      }
    }
  }
  

  package com.m2i.poe {
    package com.m2i.poe.media {
      class Dvd {
          - zone : int
          + getZone()
          + setZone()
          + Dvd()
          + Dvd()
          + getNetPrice()
      }
    }
  }
  

  package com.m2i.poe {
    package com.m2i.poe.media {
      interface IMedia {
          {abstract} + getPrice()
          {abstract} + setPrice()
          {abstract} + getId()
          {abstract} + setId()
          {abstract} + getTitle()
          {abstract} + setTitle()
          {abstract} + getNetPrice()
          {abstract} + getPublisher()
          {abstract} + setPublisher()
          {abstract} + getAuthorList()
          {abstract} + setAuthorList()
      }
    }
  }
  

  package com.m2i.poe {
    package com.m2i.poe.media {
      abstract class Media {
          - price : double
          - id : int
          - title : String
          - authorList : List<Author>
          + Media()
          + Media()
          + getPrice()
          + setPrice()
          + getId()
          + setId()
          + getTitle()
          + setTitle()
          + getNetPrice()
          + getPublisher()
          + setPublisher()
          + getAuthorList()
          + setAuthorList()
      }
    }
  }
  

  package com.m2i.poe {
    package com.m2i.poe.media {
      class MediaException {
          + MediaException()
      }
    }
  }
  

  abstract class PrintStreamOrWriter {
      - PrintStreamOrWriter()
      {abstract} ~ lock()
      {abstract} ~ println()
  }
  

  class SentinelHolder {
      {static} + STACK_TRACE_ELEMENT_SENTINEL : StackTraceElement
      {static} + STACK_TRACE_SENTINEL : StackTraceElement[]
      - SentinelHolder()
  }
  

  class WrappedPrintStream {
      - printStream : PrintStream
      ~ WrappedPrintStream()
      ~ lock()
      ~ println()
  }
  

  class WrappedPrintWriter {
      - printWriter : PrintWriter
      ~ WrappedPrintWriter()
      ~ lock()
      ~ println()
  }
  

  package com.m2i.poe {
    package com.m2i.poe.media {
      class MediaMain {
          {static} + main()
      }
    }
  }
  

  package com.m2i.poe {
    package com.m2i.poe.media {
      class Publisher {
          - id : int
          - name : String
          + Publisher()
          + Publisher()
          + getId()
          + setId()
          + getName()
          + setName()
      }
    }
  }
  

  package com.m2i.poe {
    package com.m2i.poe.media {
      class Quantity {
      }
    }
  }
  

  Book -up-|> Media
  CartRow o-- IMedia : media
  Cd -up-|> Media
  Dvd -up-|> Media
  Media -up-|> IMedia
  Media o-- Publisher : publisher
  MediaException +-down- PrintStreamOrWriter
  MediaException +-down- SentinelHolder
  MediaException +-down- WrappedPrintStream
  MediaException +-down- WrappedPrintWriter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
